# Generated by Django 4.2 on 2023-09-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_number', models.CharField(help_text='Кадастровой номер. В виде АА:ВВ:CCCCСCC:КК', max_length=20, verbose_name='Кадастровый Номеры')),
                ('latitude', models.FloatField(help_text='Значение широты', verbose_name='Широта')),
                ('longitude', models.FloatField(help_text='Значение долготы', verbose_name='Долгота')),
                ('time_came', models.DateTimeField(help_text='Время присланного запроса', verbose_name='In Time')),
                ('time_went', models.DateTimeField(blank=True, help_text='Время отправленного запроса', null=True, verbose_name='Out Time')),
                ('result_response', models.BooleanField(blank=True, help_text='Ответ внешнего сервера', null=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
                'ordering': ['-time_came'],
            },
        ),
    ]
