# Generated by Django 4.2 on 2023-09-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastral', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['-time_came'], 'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AlterField(
            model_name='query',
            name='time_came',
            field=models.DateTimeField(help_text='Время прислонного запроса', verbose_name='In Time'),
        ),
        migrations.AlterField(
            model_name='query',
            name='time_went',
            field=models.DateTimeField(help_text='Время отправленного запроса', null=True, verbose_name='Out Time'),
        ),
    ]
