# Generated by Django 4.2 on 2023-09-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastral', '0002_alter_query_options_alter_query_time_came_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='time_came',
            field=models.DateTimeField(help_text='Время присланного запроса', verbose_name='In Time'),
        ),
        migrations.AlterField(
            model_name='query',
            name='time_went',
            field=models.DateTimeField(blank=True, help_text='Время отправленного запроса', null=True, verbose_name='Out Time'),
        ),
    ]
